### ISSUE TITLE
Checkboxes Not Rendering Correctly in TwentyTwentyOne Theme

### ISSUE THREAD

**Issue by mrjarbenne** [livinglab/wp-grade-comments#20]
Checkboxes are rendering in the new WP default theme incorrectly due to this line of CSS: 

https://github.com/openlab-at-city-tech/wp-grade-comments/blob/3cc6cf0148467852ef6e6458dcb681356df16b7d/assets/css/wp-grade-comments.css#L9-L11

Removing this width attribute doesn't seem to negatively affect the display of the check boxes in older themes. 

Before:

![2021-03-09_17-05-42](https://user-images.githubusercontent.com/480667/110546990-4a814880-80fd-11eb-8458-e15d3bb8ea82.png)

With line commented out: 

![2021-03-09_17-32-19](https://user-images.githubusercontent.com/480667/110547068-6c7acb00-80fd-11eb-9bb4-ffa7cd4ee162.png)

**Comment by boonebgorges** [comment]
Thanks for the ticket. I'm unsure why this style declaration was first added - I looked back over some old tickets but couldn't find any mention of it - so I've removed it in c4ed20f.
